### ISSUE TITLE
Research Book a Tour calendar/form options

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#3]
## User Story
As a developer, I should be aware of the multiple ways in which users can input data

## AC
When I look at this ticket, 
I want to see a variety of ways in which users can input data

## Development

**Comment by sarah-weatherbee** [comment]
Link to bootstrap forms: https://getbootstrap.com/docs/4.0/components/forms/

I did not find a bootstrap form template with a datepicker, however, from my googling, I discovered that a datepicker plug-in could be integrated into the bootstrap form template.
So, we could start by using the following bootstrap basic form template code, revising as necessary so that it includes input fields for name, date to book tour, phone and email:
```html
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

**Comment by tilleraj** [comment]
@sarah-weatherbee no need for a plugin 😃 HTML 5 added the following input types ([from W3 Schools](https://www.w3schools.com/html/html_form_input_types.asp))

- color
- [Date](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date)
- [Datetime-local](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_datetime-local)
- email
- month
- number
- range
- search
- tel
- [Time](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_time)
- url
- week

They might be styled slightly differently from Bootstrap, but that can be fixed with CSS if it's bothering us. Also, importantly:  
`New input types that are not supported by older web browsers, will behave as <input type="text">.`

### Date
```html
<form action="/action_page.php">
  Birthday:
  <input type="date" name="bday">
  <input type="submit">
</form>
```
### Time
```html
<form action="/action_page.php">
  Select a time:
  <input type="time" name="usr_time">
  <input type="submit">
</form>
```
### Datetime Local
```html
<form action="/action_page.php">
  Birthday (date and time):
  <input type="datetime-local" name="bdaytime">
  <input type="submit" value="Send">
</form>
```

**Comment by mtgill** [comment]
👍
